set -g mouse on
set -g default-shell "${SHELL}"
set -g default-command "${SHELL}"
set -g @continuum-restore 'on'
set -g display-time 3000
set-option -g display-panes-time 3000
set-option -g set-clipboard on
setw -g mode-keys vi

# Copy mode -> Clipboard 
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xsel --clipboard --input"

# window
bind h split-window -h
bind v split-window -v

# prefix
set -g prefix C-b
# unbind C-b

# theme
set -g @plugin 'catppuccin/tmux#v2.1.2' # See https://github.com/catppuccin/tmux/tags for additional tags
# ...alongside
set -g @plugin 'tmux-plugins/tpm'
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'      # ヤンクを自動でクリップボードに連携
set -g @plugin 'tmux-plugins/tmux-resurrect'  # セッションをPC再起動後も復元
set -g @plugin 'tmux-plugins/tmux-continuum'  # resurrectの自動保存版

# Ctrl+b F で4分割
bind F \
  rename-window 'quad' \; \
  split-window -h \; \
  split-window -v \; \
  select-pane -t 1 \; \
  split-window -v \; \
  select-pane -t 1 \; \
  display-message 'Edit Window Name: Ctrl+b ,'

run '~/.tmux/plugins/tpm/tpm'
